"""bug table

Revision ID: 802a36befb75
Revises: 
Create Date: 2021-05-15 22:40:57.802529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '802a36befb75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=6), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bug')
    # ### end Alembic commands ###
